- [Adioso Agent, Adioso Agent (机票价格代理)]
- [Aftership Agent, Aftership Agent (快递代理)]
- [Attribute Difference Agent, Attribute Difference Agent (属性差异代理)]
- [Change Detector Agent, Change Detector Agent (属性变化代理)]
- [Commander Agent, Commander Agent (指挥官代理)]
- [Csv Agent, Csv Agent (CSV 代理)]
- [Data Output Agent, Data Output Agent (数据输出代理)]
- [De Duplication Agent, De Duplication Agent (去重代理)]
- [Delay Agent, Delay Agent (延时代理)]
- [Digest Agent, Digest Agent (合集代理)]
- [Dropbox File Url Agent, Dropbox File Url Agent (Dropbox 文件链接代理)]
- [Dropbox Watch Agent, Dropbox Watch Agent (Dropbox 监控代理)]
- [Email Agent, Email Agent (电子邮件代理)]
- [Email Digest Agent, Email Digest Agent (电子邮件合集代理)]
- [Event Formatting Agent, Event Formatting Agent (事件格式化代理)]
- [Evernote Agent, Evernote Agent (印象笔记代理)]
- [Ftpsite Agent, Ftpsite Agent (FTP 站点代理)]
- [Gap Detector Agent, Gap Detector Agent (间隙检测代理)]
- [Google Calendar Publish Agent, Google Calendar Publish Agent (Google 日历发布代理)]
- [Google Translation Agent, Google Translation Agent (Google 翻译代理)]
- [Hipchat Agent, Hipchat Agent (Hipchat 代理)]
- [Http Status Agent, Http Status Agent (HTTP 状态代理)]
- [Human Task Agent, Human Task Agent (HIT 任务代理)]
- [Imap Folder Agent, Imap Folder Agent (IMAP 文件夹代理)]
- [Jabber Agent, Jabber Agent (Jabber 账户代理)]
- [Java Script Agent, Java Script Agent (JavaScript 脚本代理)]
- [Jira Agent, Jira Agent (Jira 项目管理代理)]
- [Jq Agent, Jq Agent (Jq JSON 文件处理代理)]
- [Json Parse Agent, Json Parse Agent (JSON 解析代理)]
- [Key Value Store Agent, Key Value Store Agent (键值对储存代理)]
- [Liquid Output Agent, Liquid Output Agent (Liquid 模板解析代理)]
- [Local File Agent, Local File Agent (本地文件代理)]
- [Manual Event Agent, Manual Event Agent (手动事件代理)]
- [Mqtt Agent, Mqtt Agent (MQTT 机器间通讯代理)]
- [Pdf Info Agent, Pdf Info Agent (PDF 元数据代理)]
- [Peak Detector Agent, Peak Detector Agent (峰值检测代理)]
- [Phantom Js Cloud Agent, Phantom Js Cloud Agent (PhantomJs Cloud 网站解析代理)]
- [Post Agent, Post Agent (POST 请求代理)]
- [Public Transport Agent, Public Transport Agent (公共交通代理)]
- [Pushbullet Agent, Pushbullet Agent (Pushbullet 设备代理)]
- [Pushover Agent, Pushover Agent (Pushover 通知代理)]
- [Read File Agent, Read File Agent (文件读取代理)]
- [Rss Agent, Rss Agent (RSS 订阅代理)]
- [S3 Agent, S3 Agent (S3 云储存监控代理)]
- [Scheduler Agent, Scheduler Agent (调度器代理)]
- [Sentiment Agent, Sentiment Agent (情绪评估代理)]
- [Shell Command Agent, Shell Command Agent (Shell 命令代理)]
- [Slack Agent, Slack Agent (Slack 通知代理)]
- [Stubhub Agent, Stubhub Agent (StubHub 门票信息代理)]
- [Telegram Agent, Telegram Agent (Telegram 通知代理)]
- [Trigger Agent, Trigger Agent (触发器代理)]
- [Tumblr Likes Agent, Tumblr Likes Agent (Tumblr 点赞代理)]
- [Tumblr Publish Agent, Tumblr Publish Agent (Tumblr 发布代理)]
- [Twilio Agent, Twilio Agent (Twilio 通知代理)]
- [Twilio Receive Text Agent, Twilio Receive Text Agent (Twilio 文本接收代理)]
- [Twitter Action Agent, Twitter Action Agent (Twitter 推文代理)]
- [Twitter Favorites, Twitter Favorites (Twitter 收藏夹代理)]
- [Twitter Publish Agent, Twitter Publish Agent (Twitter 发布代理)]
- [Twitter Search Agent, Twitter Search Agent (Twitter 搜索代理)]
- [Twitter Stream Agent, Twitter Stream Agent (Twitter 推文流代理)]
- [Twitter User Agent, Twitter User Agent (Twitter 用户代理)]
- [User Location Agent, User Location Agent (物理位置代理)]
- [Weather Agent, Weather Agent (天气代理)]
- [Webhook Agent, Webhook Agent (Webhook 代理)]
- [Website Agent, Website Agent (网站爬虫代理)]
- [Weibo Publish Agent, Weibo Publish Agent (微博发布代理)]
- [Weibo User Agent, Weibo User Agent (微博用户时间线代理)]
- [Witai Agent, Witai Agent (Witai 事件代理)]
