- [every_1m, 每1分钟]
- [every_2m, 每2分钟]
- [every_5m, 每5分钟]
- [every_10m, 每10分钟]
- [every_30m, 每30分钟]
- [every_1h, 每1小时]
- [every_2h, 每2小时]
- [every_5h, 每5小时]
- [every_12h, 每12小时]
- [every_1d, 每1天]
- [every_2d, 每2天]
- [every_7d, 每7天]
- [midnight, 下午12点]
- [1am, 上午1点]
- [2am, 上午2点]
- [3am, 上午3点]
- [4am, 上午4点]
- [5am, 上午5点]
- [6am, 上午6点]
- [7am, 上午7点]
- [8am, 上午8点]
- [9am, 上午9点]
- [10am, 上午10点]
- [11am, 上午11点]
- [noon, 上午12点]
- [1pm, 下午1点]
- [2pm, 下午2点]
- [3pm, 下午3点]
- [4pm, 下午4点]
- [5pm, 下午5点]
- [6pm, 下午6点]
- [7pm, 下午7点]
- [8pm, 下午8点]
- [9pm, 下午9点]
- [10pm, 下午10点]
- [11pm, 下午11点]
- [never, 从不]
