name: Build Huginn Docker Images CI

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-huginn-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout local translate
        uses: actions/checkout@v3
        with:
          repository: 'yhdsl/Huginn-Chinese'
          path: './translate'

      - name: Checkout translator tool
        uses: actions/checkout@v3
        with:
          repository: 'yhdsl/Translator-Tool'
          path: './tool'

      - name: Checkout Huginn source code
        uses: actions/checkout@v3
        with:
          repository: 'huginn/huginn'
          path: './huginn'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Copy i18n files
        run: mv -f ./translate/huginn/* ./huginn

      - name: Run translator tool
        run: python ./tool/translator.py ./translate/rules -r $(pwd)/huginn

      - name: Copy Dockerfile
        run: mv ./huginn/docker/multi-process/Dockerfile ./huginn

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./huginn
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/huginn:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
